version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgres://localhost:5432
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata:
